export const WEATHER_DATA_REQUEST = 'WEATHER_DATA_REQUEST';
export const WEATHER_DATA_SUCCESS = 'WEATHER_DATA_SUCCESS';
export const WEATHER_DATA_ERROR = 'WEATHER_DATA_ERROR';

export const REVERSE_GEOCODING_REQUEST = 'REVERSE_GEOCODING_REQUEST';
export const REVERSE_GEOCODING_SUCCESS = 'REVERSE_GEOCODING_SUCCESS';
export const REVERSE_GEOCODING_ERROR = 'REVERSE_GEOCODING_ERROR';

export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_ERROR = 'AUTOCOMPLETE_ERROR';
export const AUTOCOMPLETE_RESET = 'AUTOCOMPLETE_RESET';