export const WEATHER_DATA_REQUEST = 'WEATHER_DATA_REQUEST';
export const WEATHER_DATA_SUCCESS = 'WEATHER_DATA_SUCCESS';
export const WEATHER_DATA_ERROR = 'WEATHER_DATA_ERROR';

export const REVERSE_GEOCODING_REQUEST = 'REVERSE_GEOCODING_REQUEST';
export const REVERSE_GEOCODING_SUCCESS = 'REVERSE_GEOCODING_SUCCESS';
export const REVERSE_GEOCODING_ERROR = 'REVERSE_GEOCODING_ERROR';

export const GEOCODING_REQUEST = 'GEOCODING_REQUEST';
export const GEOCODING_SUCCESS = 'GEOCODING_SUCCESS';
export const GEOCODING_ERROR = 'GEOCODING_ERROR';

export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_ERROR = 'AUTOCOMPLETE_ERROR';
export const AUTOCOMPLETE_RESET = 'AUTOCOMPLETE_RESET';

export const SAVE_LOCATION_REQUEST = 'SAVE_LOCATION_REQUEST';
export const DELETE_LOCATION_REQUEST = 'DELETE_LOCATION_REQUEST';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const SET_PREFERENCE = 'SET_PREFERENCE';

export const SET_FIRST_LAUNCH = 'SET_FIRST_LAUNCH';
