export const WEATHER_DATA_REQUEST = 'WEATHER_DATA_REQUEST';
export const WEATHER_DATA_SUCCESS = 'WEATHER_DATA_SUCCESS';
export const WEATHER_DATA_ERROR = 'WEATHER_DATA_ERROR';

export const SET_LOCATION_REQUEST = 'SET_LOCATION_REQUEST';
export const SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS';
export const SET_LOCATION_ERROR = 'SET_LOCATION_ERROR';

export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';

export const REVERSE_GEOCODING_REQUEST = 'REVERSE_GEOCODING_REQUEST';
export const REVERSE_GEOCODING_SUCCESS = 'REVERSE_GEOCODING_SUCCESS';
export const REVERSE_GEOCODING_ERROR = 'REVERSE_GEOCODING_ERROR';